export const LOGIN_ERROR="LOGIN_ERROR";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_LOADING="LOGIN_LOADING";
export const LOGOUT_USER="LOGOUT_USER";
export const GOOGLE_AUTH="GOOGLE_AUTH";