export const POST_BLOG_SUCCESS="POST_BLOG_SUCCESS";
export const POST_BLOG_ERROR="POST_BLOG_ERROR";
export const POST_BLOG_LOADING="POST_BLOG_LOADING"
export const GET_BLOG_LOADING="GET_BLOG_ERROR";
export const GET_BLOG_SUCCESS="GET_BLOG_SUCCESS";
export const GET_BLOG_ERROR="GET_BLOG_ERROR";