export const FORGOTPASS_ERROR="FORGOTPASS_ERROR";
export const FORGOTPASS_SUCCESS="FORGOTPASS_SUCCESS";
export const FORGOTPASS_LOADING="FORGOTPASS_LOADING";
export const SET_FORGOTPASS_ERROR="SET_FORGOTPASS_ERROR";
export const SET_FORGOTPASS_SUCCESS="SET_FORGOTPASS_SUCCESS";
export const SET_FORGOTPASS_LOADING="SET_FORGOTPASS_LOADING";